openapi: 3.0.0
info:
  title: Bank Account Service
  description: API to manage bank accounts.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /v1/credits:
    get:
      summary: Get all credits
      operationId: getAllCredits
      responses:
        '200':
          description: List of credits
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreditResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create a new account
      operationId: createCredit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditRequest'
      responses:
        '201':
          description: Account created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/credits/{creditId}:
    get:
      summary: Get an credit by ID
      operationId: getCreditById
      parameters:
        - name: creditId
          in: path
          required: true
          description: Id of account
          schema:
            type: string
      responses:
        '200':
          description: Credit found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditResponse'
        '404':
          description: Credit not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Update an credit by ID
      operationId: updateCredit
      parameters:
        - name: creditId
          in: path
          required: true
          description: Id of credit
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditRequest'
      responses:
        '200':
          description: Account updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Delete an credit by ID
      operationId: deleteCredit
      parameters:
        - name: creditId
          in: path
          required: true
          description: Id of credit
          schema:
            type: string
      responses:
        '204':
          description: Credit deleted
        '404':
          description: Credit not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/credit/{creditId}/withdrawal:
    post:
      summary: Make a withdraw from an credit
      operationId: withdrawFromCredit
      parameters:
        - name: creditId
          in: path
          required: true
          description: Id of credit
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
      responses:
        '200':
          description: Withdrawal made
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        '404':
          description: Credit not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Insufficient funds
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/credit/{creditId}/balances:
    get:
      summary: Get client balances
      operationId: getClientBalances
      parameters:
        - name: creditId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Client balances
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
        '404':
          description: Client not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/account/{creditId}/transactions:
    get:
      summary: Get client transactions
      operationId: getClientTransactions
      parameters:
        - name: creditId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of Transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransactionResponse'
        '404':
          description: Client not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CreditRequest:
      type: object
      properties:
        type:
          type: string
          enum: [personal,business]
        creditLimit:
          type: number
        amount:
          type: number
        interestRate:
          type: number
        clientId:
          type: string
      required:
        - type
        - clientId
        - amount
        - interestRate
        - creditLimit
    CreditResponse:
      type: object
      properties:
        _id:
          type: string
        creditNumber:
          type: string
        type:
          type: string
          enum: [ personal,business ]
        creditLimit:
          type: number
        amount:
          type: number
        interestRate:
          type: number
        clientId:
          type: string
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
    Transaction:
      type: object
      properties:
        clientId:
          type: string
        type:
          type: string
          enum: [deposit, withdrawal]
        amount:
          type: number
        date:
          type: string
          format: date
        description:
          type: string
    TransactionRequest:
      type: object
      required:
        - bankAccountId
        - clientId
        - amount
      properties:
        bankAccountId:
          type: string
        type:
          type: string
          enum: [ deposit,withdrawal ]
        amount:
          type: number
          format: double
        description:
          type: string
        clientId:
          type: string
        balance:
          type: number
          format: double
    TransactionResponse:
      type: object
      required:
        - clientId
        - bankAccountId
      properties:
        bankAccountId:
          type: string
        type:
          type: string
          enum: [ deposit,withdrawal ]
        amount:
          type: number
        clientId:
          type: string
    BalanceResponse:
      type: object
      properties:
        clientId:
          type: string
        balance:
          type: number
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
